#!/bin/sh
V="
count_letters_85
count_letters_90
count_letters_95
count_letters_98
count_letters_99
count_letters_99.9
max_letters
sample_objectness_letters
objectness_letters
"
for v in $V;do python scripts/obox.py --field="stats.out_of_the_box_classification.letterness.$v" --model-folder=tools/models/external/fonts_and_digits --name="letterness#$v"; done
