#!/bin/sh
F="stats.out_of_the_box_classification.fonts.objectness"
lightjob show --fields="summary,$F,stats.out_of_the_box_classification.m2.objectness" --sort=$F --state=success --details --descending
